ALTER TABLE person_implementation DROP FOREIGN KEY FKperson_imp834479;
ALTER TABLE person_implementation DROP FOREIGN KEY FKperson_imp61685;
ALTER TABLE subgroup_implementation DROP FOREIGN KEY FKsubgroup_i536038;
ALTER TABLE subgroup_implementation DROP FOREIGN KEY FKsubgroup_i746979;
ALTER TABLE room_implementation DROP FOREIGN KEY FKroom_imple506436;
ALTER TABLE room_implementation DROP FOREIGN KEY FKroom_imple977683;
ALTER TABLE subgroup DROP FOREIGN KEY FKsubgroup179933;
ALTER TABLE `group` DROP FOREIGN KEY FKgroup987729;
ALTER TABLE curriculum DROP FOREIGN KEY FKcurriculum190929;
ALTER TABLE implementation DROP FOREIGN KEY FKimplementa589065;
ALTER TABLE course DROP FOREIGN KEY FKcourse108073;
ALTER TABLE person_degreeprogram DROP FOREIGN KEY FKperson_deg701896;
ALTER TABLE person_degreeprogram DROP FOREIGN KEY FKperson_deg769719;
DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS `group`;
DROP TABLE IF EXISTS curriculum;
DROP TABLE IF EXISTS subgroup;
DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS course;
DROP TABLE IF EXISTS degreeprogram;
DROP TABLE IF EXISTS implementation;
DROP TABLE IF EXISTS person_implementation;
DROP TABLE IF EXISTS subgroup_implementation;
DROP TABLE IF EXISTS room_implementation;
DROP TABLE IF EXISTS person_degreeprogram;
CREATE TABLE person (id int(11) NOT NULL AUTO_INCREMENT, Code varchar(7) NOT NULL UNIQUE, Name varchar(50) NOT NULL UNIQUE, PRIMARY KEY (id), UNIQUE INDEX (id)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE `group` (id int(11) NOT NULL AUTO_INCREMENT, Code varchar(20) NOT NULL, degreeprogramid int(11) NOT NULL, PRIMARY KEY (id), UNIQUE INDEX (id), UNIQUE INDEX (Code)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE curriculum (id int(10) NOT NULL AUTO_INCREMENT, Name varchar(30), degreeprogramid int(11) NOT NULL, PRIMARY KEY (id), UNIQUE INDEX (id)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE subgroup (id int(11) NOT NULL AUTO_INCREMENT, Code varchar(20) NOT NULL, Department varchar(30) NOT NULL, groupid int(11) NOT NULL, PRIMARY KEY (id), UNIQUE INDEX (id), UNIQUE INDEX (Code)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE room (id int(11) NOT NULL AUTO_INCREMENT, Code varchar(50) NOT NULL, Seats int(10), Topic varchar(50), PRIMARY KEY (id), UNIQUE INDEX (id), UNIQUE INDEX (Code)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE course (id int(11) NOT NULL AUTO_INCREMENT, Code varchar(20) NOT NULL, Name varchar(50), Changes varchar(50), Languages varchar(50), Credit int(11), `Size` int(11), P1 int(11), P2 int(11), P3 int(11), P4 int(11), P5 int(11), Total int(11), curriculumid int(10) NOT NULL, PRIMARY KEY (id), UNIQUE INDEX (id), UNIQUE INDEX (Code)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE degreeprogram (id int(11) NOT NULL AUTO_INCREMENT, Code varchar(10) NOT NULL, Name varchar(50), PRIMARY KEY (id), UNIQUE INDEX (id), UNIQUE INDEX (Code)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE implementation (id int(11) NOT NULL AUTO_INCREMENT, courseid int(11) NOT NULL, PRIMARY KEY (id), UNIQUE INDEX (id)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE person_implementation (personid int(11) NOT NULL, implementationid int(11) NOT NULL, PRIMARY KEY (personid, implementationid)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE subgroup_implementation (subgroupid int(11) NOT NULL, implementationid int(11) NOT NULL, PRIMARY KEY (subgroupid, implementationid)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE room_implementation (roomid int(11) NOT NULL, implementationid int(11) NOT NULL, PRIMARY KEY (roomid, implementationid)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE person_degreeprogram (personid int(11) NOT NULL, degreeprogramid int(11) NOT NULL, PRIMARY KEY (personid, degreeprogramid)) ENGINE=InnoDB CHARACTER SET UTF8;
ALTER TABLE person_implementation ADD INDEX FKperson_imp834479 (personid), ADD CONSTRAINT FKperson_imp834479 FOREIGN KEY (personid) REFERENCES person (id);
ALTER TABLE person_implementation ADD INDEX FKperson_imp61685 (implementationid), ADD CONSTRAINT FKperson_imp61685 FOREIGN KEY (implementationid) REFERENCES implementation (id);
ALTER TABLE subgroup_implementation ADD INDEX FKsubgroup_i536038 (subgroupid), ADD CONSTRAINT FKsubgroup_i536038 FOREIGN KEY (subgroupid) REFERENCES subgroup (id);
ALTER TABLE subgroup_implementation ADD INDEX FKsubgroup_i746979 (implementationid), ADD CONSTRAINT FKsubgroup_i746979 FOREIGN KEY (implementationid) REFERENCES implementation (id);
ALTER TABLE room_implementation ADD INDEX FKroom_imple506436 (roomid), ADD CONSTRAINT FKroom_imple506436 FOREIGN KEY (roomid) REFERENCES room (id);
ALTER TABLE room_implementation ADD INDEX FKroom_imple977683 (implementationid), ADD CONSTRAINT FKroom_imple977683 FOREIGN KEY (implementationid) REFERENCES implementation (id);
ALTER TABLE subgroup ADD INDEX FKsubgroup179933 (groupid), ADD CONSTRAINT FKsubgroup179933 FOREIGN KEY (groupid) REFERENCES `group` (id);
ALTER TABLE `group` ADD INDEX FKgroup987729 (degreeprogramid), ADD CONSTRAINT FKgroup987729 FOREIGN KEY (degreeprogramid) REFERENCES degreeprogram (id);
ALTER TABLE curriculum ADD INDEX FKcurriculum190929 (degreeprogramid), ADD CONSTRAINT FKcurriculum190929 FOREIGN KEY (degreeprogramid) REFERENCES degreeprogram (id);
ALTER TABLE implementation ADD INDEX FKimplementa589065 (courseid), ADD CONSTRAINT FKimplementa589065 FOREIGN KEY (courseid) REFERENCES course (id);
ALTER TABLE course ADD INDEX FKcourse108073 (curriculumid), ADD CONSTRAINT FKcourse108073 FOREIGN KEY (curriculumid) REFERENCES curriculum (id);
ALTER TABLE person_degreeprogram ADD INDEX FKperson_deg701896 (personid), ADD CONSTRAINT FKperson_deg701896 FOREIGN KEY (personid) REFERENCES person (id);
ALTER TABLE person_degreeprogram ADD INDEX FKperson_deg769719 (degreeprogramid), ADD CONSTRAINT FKperson_deg769719 FOREIGN KEY (degreeprogramid) REFERENCES degreeprogram (id);
